Fix minor issues. Issue 01 : Error "TypeError: 'bool' object is not callable"            Issue occurred when calling set_log_mode function twice.            function name and variable name is same. Change function name to set_apdu_timing
Issue 02 : AttributeError: type object 'PSS' has no attribute 'PSS'
           Issue occurred when calling RSA_signature/RSA_verify. PSS used twice. PSS.PSS -> PSS

Issue 03 : terminal() return error in case of there is several reader which connected to PC.
           Issue occurred because of for loop. quit the for loop when card detected.

Issue 04 : global variable "current_selected_aid" not necessary anymore. securityInfo dictionary contain select AID information.